// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChzIMG0sT54dyd0SZMarQhLULMaOmZvEs',
    appId: '1:174184332140:web:9cee3639ded871c2bc5149',
    messagingSenderId: '174184332140',
    projectId: 'atlas-c83be',
    authDomain: 'atlas-c83be.firebaseapp.com',
    storageBucket: 'atlas-c83be.firebasestorage.app',
    measurementId: 'G-W2QE62XMTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApsxMIqkZexsAcWGNBj8cT39Xp0OfQCtk',
    appId: '1:174184332140:android:03da4ca020a2ac67bc5149',
    messagingSenderId: '174184332140',
    projectId: 'atlas-c83be',
    storageBucket: 'atlas-c83be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKSuVD-2G3JzJitr4TYj37PZAiMdIKvxk',
    appId: '1:174184332140:ios:0cdef9b1d62ada73bc5149',
    messagingSenderId: '174184332140',
    projectId: 'atlas-c83be',
    storageBucket: 'atlas-c83be.firebasestorage.app',
    iosBundleId: 'com.jamesbriggs.atlas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKSuVD-2G3JzJitr4TYj37PZAiMdIKvxk',
    appId: '1:174184332140:ios:37e25acfb429a100bc5149',
    messagingSenderId: '174184332140',
    projectId: 'atlas-c83be',
    storageBucket: 'atlas-c83be.firebasestorage.app',
    iosBundleId: 'com.example.atlas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChzIMG0sT54dyd0SZMarQhLULMaOmZvEs',
    appId: '1:174184332140:web:b2f45099711d4dafbc5149',
    messagingSenderId: '174184332140',
    projectId: 'atlas-c83be',
    authDomain: 'atlas-c83be.firebaseapp.com',
    storageBucket: 'atlas-c83be.firebasestorage.app',
    measurementId: 'G-EV9YNW0MC2',
  );
}
